import Foundation

/// Describes one `.cube` file bundled with the app.
///
/// This is deliberately a small value type, not a management framework: it
/// records what a LUT is and where to find it so a future LUT stage can look it
/// up. It performs no rendering and touches none of the existing grading tools.
struct LUTAsset: Equatable, Sendable, Identifiable {
    /// Where a look's `.cube` file comes from.
    enum Origin: String, Equatable, Sendable {
        /// Generated by `Tools/LUTGenerator` and shipped in the bundle.
        case builtIn
        /// Dropped into `Resources/LUTs/Imported` before the build.
        case bundled
        /// Imported by the user at runtime; stored in Application Support.
        case device
    }

    /// What the LUT does to the image.
    enum Kind: String, Equatable, Sendable {
        /// A look. Expects footage already in the working SDR space.
        case creative
        /// A colour-space or camera conversion. None are bundled yet; those
        /// belong to a separate technical stage, not to this creative list.
        case technical
    }

    let name: String
    let filename: String
    let category: String
    let summary: String
    /// The colour space this LUT expects on input.
    let inputColorSpace: String
    let kind: Kind
    /// Where the file lives, which decides how `url` resolves it.
    var origin: Origin = .builtIn

    var id: String { filename }

    /// Resource name without the `.cube` extension.
    var resourceName: String {
        (filename as NSString).deletingPathExtension
    }

    var isBuiltIn: Bool { origin == .builtIn }

    /// The file's own extension, which is not always lowercase: `.CUBE` is just
    /// as common as `.cube` in look packs.
    var fileExtension: String { (filename as NSString).pathExtension }

    /// Imported looks resolve against Application Support; the rest against the
    /// app bundle.
    func url(in bundle: Bundle = .lutResources) -> URL? {
        switch origin {
        case .builtIn, .bundled:
            // Resolved by filename rather than through
            // `url(forResource:withExtension:)`, which matches the extension
            // case-sensitively and so cannot find `Serenity.CUBE` when asked
            // for "cube". Names with spaces resolve here too.
            if let direct = bundle.resourceURL?.appendingPathComponent(filename),
               FileManager.default.fileExists(atPath: direct.path) {
                return direct
            }
            return bundle.url(forResource: resourceName, withExtension: fileExtension)
        case .device:
            let url = LUTStore.directory.appendingPathComponent(filename)
            return FileManager.default.fileExists(atPath: url.path) ? url : nil
        }
    }

    /// Both kinds of imported look take their display name from the filename,
    /// with underscores read as spaces, so `Night_Market.cube` reads
    /// "Night Market".
    static func displayName(forResourceName name: String) -> String {
        name.replacingOccurrences(of: "_", with: " ")
    }

    static func imported(resourceName: String) -> LUTAsset {
        LUTAsset(
            name: displayName(forResourceName: resourceName),
            filename: "\(resourceName).cube",
            category: "Imported",
            summary: "Imported look.",
            inputColorSpace: "Rec.709 / working SDR",
            kind: .creative,
            origin: .device
        )
    }
}

/// Resolves the bundle that actually carries the `.cube` resources. In the app
/// that is the main bundle; under XCTest `Bundle.main` is the test runner, so
/// the lookup has to go through a type that lives in the app itself.
private final class LUTBundleToken {}

extension Bundle {
    static let lutResources = Bundle(for: LUTBundleToken.self)
}

extension LUTAsset {
    /// Looks that ship inside the app: the three curated ones first, then any
    /// `.cube` dropped into `Resources/LUTs/Imported` before the build.
    ///
    /// Discovery is what makes that folder work — adding a file and rebuilding
    /// is enough, with no code change.
    /// Files in the looks folder that cannot be offered as looks.
    ///
    /// Only Apple's 1D Log-to-linear curve, and only because a 1D LUT is not
    /// something the look stage can apply at all — it would appear as a tile
    /// that does nothing. Apple's Log-to-Rec.709 cube stays in the list: it is
    /// a technical conversion rather than a creative look, but it is a usable
    /// one, and hiding a file someone deliberately added is worse than letting
    /// them choose it.
    static let technicalTransformResourceNames: Set<String> = [
        "Apple_Log_1"
    ]

    static let bundledLooks: [LUTAsset] = {
        let builtIn = bundledCreativeLooks
        let known = Set(builtIn.map(\.resourceName)).union(technicalTransformResourceNames)
        // The resource directory is listed directly. `urls(forResourcesWithExtension:)`
        // matches the extension case-sensitively, so asking it for "cube" silently
        // skipped every look shipped as `.CUBE` — which is a common way for look
        // packs to name them.
        let contents = Bundle.lutResources.resourceURL.map {
            (try? FileManager.default.contentsOfDirectory(at: $0, includingPropertiesForKeys: nil)) ?? []
        } ?? []
        let discovered = contents
            .filter { $0.pathExtension.lowercased() == "cube" }
            .map { $0.lastPathComponent }
            .filter { !known.contains(($0 as NSString).deletingPathExtension) }
            .sorted { $0.localizedStandardCompare($1) == .orderedAscending }
            .map { filename in
                let resourceName = (filename as NSString).deletingPathExtension
                return LUTAsset(
                    name: displayName(forResourceName: resourceName),
                    filename: filename,
                    category: "Imported",
                    summary: "Imported look.",
                    inputColorSpace: "Rec.709 / working SDR",
                    kind: .creative,
                    origin: .bundled
                )
            }
        return builtIn + discovered
    }()

    /// Every look available right now, including ones the user imported from
    /// their device. Not cached, because device imports change while the app is
    /// running; it reads a small directory listing, so callers should hold the
    /// result rather than call it inside a view body.
    static var allLooks: [LUTAsset] {
        bundledLooks + LUTStore.installedLooks()
    }

    /// The creative looks generated by `Tools/LUTGenerator`.
    ///
    /// All of these expect Rec.709 / working SDR input, matching the app's
    /// validated V1 support boundary. Log and HDR conversions are not creative
    /// looks and are not listed here.
    static let bundledCreativeLooks: [LUTAsset] = [
        LUTAsset(
            name: "Warm Cinema",
            filename: "Warm_Cinema.cube",
            category: "Cinematic",
            summary: "Warm, contrasty cinematic look with soft highlights and flattering skin tones.",
            inputColorSpace: "Rec.709 / working SDR",
            kind: .creative
        ),
        LUTAsset(
            name: "Teal Orange",
            filename: "Teal_Orange.cube",
            category: "Cinematic",
            summary: "Restrained modern teal-shadow / warm-highlight look with controlled greens.",
            inputColorSpace: "Rec.709 / working SDR",
            kind: .creative
        ),
        LUTAsset(
            name: "Soft Film",
            filename: "Soft_Film.cube",
            category: "Film-inspired",
            summary: "Soft, slightly faded look with lifted blacks, muted colour and smooth highlights.",
            inputColorSpace: "Rec.709 / working SDR",
            kind: .creative
        )
    ]
}
