import Foundation

/// Describes one `.cube` file bundled with the app.
///
/// This is deliberately a small value type, not a management framework: it
/// records what a LUT is and where to find it so a future LUT stage can look it
/// up. It performs no rendering and touches none of the existing grading tools.
struct LUTAsset: Equatable, Sendable, Identifiable {
    /// Where a look's `.cube` file comes from.
    enum Origin: String, Equatable, Sendable {
        /// Generated by `Tools/LUTGenerator` and shipped in the bundle.
        case builtIn
        /// Dropped into `Resources/LUTs/Imported` before the build.
        case bundled
        /// Imported by the user at runtime; stored in Application Support.
        case device
    }

    /// What the LUT does to the image.
    enum Kind: String, Equatable, Sendable {
        /// A look. Expects footage already in the working SDR space.
        case creative
        /// A colour-space or camera conversion. None are bundled yet; those
        /// belong to a separate technical stage, not to this creative list.
        case technical
    }

    let name: String
    let filename: String
    let category: String
    let summary: String
    /// The colour space this LUT expects on input.
    let inputColorSpace: String
    let kind: Kind
    /// Where the file lives, which decides how `url` resolves it.
    var origin: Origin = .builtIn

    var id: String { filename }

    /// Resource name without the `.cube` extension.
    var resourceName: String {
        (filename as NSString).deletingPathExtension
    }

    var isBuiltIn: Bool { origin == .builtIn }

    /// The file's own extension, which is not always lowercase: `.CUBE` is just
    /// as common as `.cube` in look packs.
    var fileExtension: String { (filename as NSString).pathExtension }

    /// The compiled form's filename.
    ///
    /// Deliberately the text filename with a suffix appended — `Nomad.cube`
    /// compiles to `Nomad.cube.gclut` — rather than a replaced extension.
    /// `filename` is this look's identity, and it is what `AdvancedGrade.lut`
    /// saved into every project that uses the look; replacing the extension
    /// would change that identity, and `Serenity.CUBE` and `Serenity.cube`
    /// would both collapse onto the same compiled name. Appending keeps the
    /// identity recoverable by removing exactly one extension.
    var compiledFilename: String { "\(filename).\(LUTBinary.fileExtension)" }

    /// Imported looks resolve against Application Support; the rest against the
    /// app bundle.
    func url(in bundle: Bundle = .lutResources) -> URL? {
        switch origin {
        case .builtIn, .bundled:
            // Resolved by filename rather than through
            // `url(forResource:withExtension:)`, which matches the extension
            // case-sensitively and so cannot find `Serenity.CUBE` when asked
            // for "cube". Names with spaces resolve here too.
            //
            // The compiled form wins wherever it shipped: it is the same look
            // at a fifth of the bytes. The text form is still resolved after
            // it, so a `.cube` dropped into the folder without being compiled
            // keeps working exactly as it did.
            if let root = bundle.resourceURL {
                for candidate in [compiledFilename, filename] {
                    let url = root.appendingPathComponent(candidate)
                    if FileManager.default.fileExists(atPath: url.path) { return url }
                }
            }
            return bundle.url(forResource: resourceName, withExtension: fileExtension)
        case .device:
            let url = LUTStore.directory.appendingPathComponent(filename)
            return FileManager.default.fileExists(atPath: url.path) ? url : nil
        }
    }

    /// Both kinds of imported look take their display name from the filename,
    /// with underscores read as spaces, so `Night_Market.cube` reads
    /// "Night Market".
    static func displayName(forResourceName name: String) -> String {
        name.replacingOccurrences(of: "_", with: " ")
    }

    static func imported(resourceName: String) -> LUTAsset {
        LUTAsset(
            name: displayName(forResourceName: resourceName),
            filename: "\(resourceName).cube",
            category: "Imported",
            summary: String(localized: "Imported look."),
            inputColorSpace: "Rec.709 / working SDR",
            kind: .creative,
            origin: .device
        )
    }
}

/// Resolves the bundle that actually carries the `.cube` resources. In the app
/// that is the main bundle; under XCTest `Bundle.main` is the test runner, so
/// the lookup has to go through a type that lives in the app itself.
private final class LUTBundleToken {}

extension Bundle {
    static let lutResources = Bundle(for: LUTBundleToken.self)
}

extension LUTAsset {
    /// Looks that ship inside the app: the three curated ones first, then any
    /// `.cube` dropped into `Resources/LUTs/Imported` before the build.
    ///
    /// Discovery is what makes that folder work — adding a file and rebuilding
    /// is enough, with no code change.
    /// Files in the looks folder that cannot be offered as looks.
    ///
    /// Only Apple's 1D Log-to-linear curve, and only because a 1D LUT is not
    /// something the look stage can apply at all — it would appear as a tile
    /// that does nothing. Apple's Log-to-Rec.709 cube stays in the list: it is
    /// a technical conversion rather than a creative look, but it is a usable
    /// one, and hiding a file someone deliberately added is worse than letting
    /// them choose it.
    static let technicalTransformResourceNames: Set<String> = [
        "Apple_Log_1"
    ]

    static let bundledLooks: [LUTAsset] = {
        let builtIn = bundledCreativeLooks + bundledLogConversions
        let known = Set(builtIn.map(\.resourceName)).union(technicalTransformResourceNames)
        // The resource directory is listed directly. `urls(forResourcesWithExtension:)`
        // matches the extension case-sensitively, so asking it for "cube" silently
        // skipped every look shipped as `.CUBE` — which is a common way for look
        // packs to name them.
        let contents = Bundle.lutResources.resourceURL.map {
            (try? FileManager.default.contentsOfDirectory(at: $0, includingPropertiesForKeys: nil)) ?? []
        } ?? []
        // A look ships either compiled (`Nomad.cube.gclut`) or as plain text
        // (`Nomad.cube`). Both are listed and reduced to the text filename,
        // which is the look's identity either way, so a folder holding both
        // forms of the same look still offers it once.
        var seen = Set<String>()
        let discovered = contents
            .map(\.lastPathComponent)
            .compactMap { name -> String? in
                let identity = name.hasSuffix(".\(LUTBinary.fileExtension)")
                    ? String(name.dropLast(LUTBinary.fileExtension.count + 1))
                    : name
                return (identity as NSString).pathExtension.lowercased() == "cube" ? identity : nil
            }
            .filter { !known.contains(($0 as NSString).deletingPathExtension) && seen.insert($0).inserted }
            .sorted { $0.localizedStandardCompare($1) == .orderedAscending }
            .map { filename in
                let resourceName = (filename as NSString).deletingPathExtension
                return LUTAsset(
                    name: displayName(forResourceName: resourceName),
                    filename: filename,
                    category: "Imported",
                    summary: String(localized: "Imported look."),
                    inputColorSpace: "Rec.709 / working SDR",
                    kind: .creative,
                    origin: .bundled
                )
            }
        return builtIn + discovered
    }()

    /// Every look available right now, including ones the user imported from
    /// their device. Not cached, because device imports change while the app is
    /// running; it reads a small directory listing, so callers should hold the
    /// result rather than call it inside a view body.
    static var allLooks: [LUTAsset] {
        bundledLooks + LUTStore.installedLooks()
    }

    /// The creative looks generated by `Tools/LUTGenerator`.
    ///
    /// All of these expect Rec.709 / working SDR input, matching the app's
    /// validated V1 support boundary. Log and HDR conversions are not creative
    /// looks and are not listed here.
    static let bundledCreativeLooks: [LUTAsset] = [
        LUTAsset(
            name: "Warm Cinema",
            filename: "Warm_Cinema.cube",
            category: "Cinematic",
            summary: String(localized: "Warm, contrasty cinematic look with soft highlights and flattering skin tones."),
            inputColorSpace: "Rec.709 / working SDR",
            kind: .creative
        ),
        LUTAsset(
            name: "Teal Orange",
            filename: "Teal_Orange.cube",
            category: "Cinematic",
            summary: String(localized: "Restrained modern teal-shadow / warm-highlight look with controlled greens."),
            inputColorSpace: "Rec.709 / working SDR",
            kind: .creative
        ),
        LUTAsset(
            name: "Soft Film",
            filename: "Soft_Film.cube",
            category: "Film-inspired",
            summary: String(localized: "Soft, slightly faded look with lifted blacks, muted colour and smooth highlights."),
            inputColorSpace: "Rec.709 / working SDR",
            kind: .creative
        )
    ]

    /// Sony's own Log conversion transforms, for footage the app cannot decode
    /// natively the way it decodes Apple Log.
    ///
    /// These are `.technical`, not looks, and they are a deliberate exception to
    /// the rule the imported-looks guide states: a conversion LUT is the wrong
    /// thing to apply to Rec.709 footage. It is the *right* thing to apply to
    /// the footage it names, and the look stage runs before the grading tools
    /// (see `applyLookAndGrade`), which is exactly where an input transform
    /// belongs. So the pipeline position is already correct; what is missing is
    /// only a stage that would pick one automatically.
    ///
    /// Listed explicitly rather than left to discovery because discovery labels
    /// everything it finds as a creative look expecting Rec.709 input, which
    /// would describe these as the opposite of what they are. Kept out of
    /// `bundledCreativeLooks` for a harder reason: `BundledLUTTests` requires a
    /// creative look to be 33-point and to map black to black and white to
    /// white. A Log transform does neither — S-Log3 black sits at 0.0929, not 0
    /// — so it would fail tests that are correct to demand that of a look.
    ///
    /// `origin` is `.bundled` rather than `.builtIn` so they are not preloaded
    /// at launch: eight more looks, two of them 65-point, is not the "cheaper
    /// than the bookkeeping" trade `preloadBundledLooks` is written for. They
    /// load on first selection like any other bundled look.
    static let bundledLogConversions: [LUTAsset] = [
        LUTAsset(
            name: "S-Log3 to LC-709",
            filename: "SLog3_LC709.cube",
            category: "Sony Log",
            summary: String(localized: "Sony's neutral low-contrast conversion. The flattest starting point, with the most room left to grade."),
            inputColorSpace: "S-Log3 / S-Gamut3.Cine",
            kind: .technical,
            origin: .bundled
        ),
        LUTAsset(
            name: "S-Log3 to LC-709 Type A",
            filename: "SLog3_LC709TypeA.cube",
            category: "Sony Log",
            summary: String(localized: "Low contrast with Sony's Type A rendering, tuned to sit closer to an ARRI Alexa."),
            inputColorSpace: "S-Log3 / S-Gamut3.Cine",
            kind: .technical,
            origin: .bundled
        ),
        LUTAsset(
            name: "S-Log3 to Cine 709",
            filename: "SLog3_Cine709.cube",
            category: "Sony Log",
            summary: String(localized: "Sony's Cine+709 conversion: more contrast and a film-style curve, ready to watch with less grading."),
            inputColorSpace: "S-Log3 / S-Gamut3.Cine",
            kind: .technical,
            origin: .bundled
        ),
        LUTAsset(
            name: "S-Log3 to S-Log2 709",
            filename: "SLog3_SLog2709.cube",
            category: "Sony Log",
            summary: String(localized: "Converts S-Log3 with the older S-Log2 709 rendering, for matching footage shot on both."),
            inputColorSpace: "S-Log3 / S-Gamut3.Cine",
            kind: .technical,
            origin: .bundled
        ),
        LUTAsset(
            name: "S-Log2 to LC-709",
            filename: "SLog2_LC709.cube",
            category: "Sony Log",
            summary: String(localized: "Sony's neutral low-contrast conversion for S-Log2 footage from older Sony bodies."),
            inputColorSpace: "S-Log2 / S-Gamut",
            kind: .technical,
            origin: .bundled
        ),
        LUTAsset(
            name: "S-Log2 to LC-709 Type A",
            filename: "SLog2_LC709TypeA.cube",
            category: "Sony Log",
            summary: String(localized: "Low contrast with Sony's Type A rendering, for S-Log2 footage."),
            inputColorSpace: "S-Log2 / S-Gamut",
            kind: .technical,
            origin: .bundled
        ),
        LUTAsset(
            name: "S-Log2 to Cine 709",
            filename: "SLog2_Cine709.cube",
            category: "Sony Log",
            summary: String(localized: "Sony's Cine+709 conversion for S-Log2: more contrast and a film-style curve."),
            inputColorSpace: "S-Log2 / S-Gamut",
            kind: .technical,
            origin: .bundled
        ),
        LUTAsset(
            name: "S-Log2 to S-Log2 709",
            filename: "SLog2_SLog2709.cube",
            category: "Sony Log",
            summary: String(localized: "Sony's standard S-Log2 709 rendering, the closest match to the camera's own monitoring."),
            inputColorSpace: "S-Log2 / S-Gamut",
            kind: .technical,
            origin: .bundled
        ),
        // Shipped loose in the looks folder before this list existed, which is
        // why its filename is the one DJI published rather than a tidy one: that
        // string is the look's identity and is what any project already using it
        // has saved. The display name is set here instead.
        LUTAsset(
            name: "DJI D-Log M to Rec.709",
            filename: "DJI Mavic 3 D-Log M to Rec.709 V1.cube",
            category: "DJI Log",
            summary: String(localized: "DJI's conversion for D-Log M footage from Mavic 3 and other DJI cameras."),
            inputColorSpace: "DJI D-Log M",
            kind: .technical,
            origin: .bundled
        )
    ]
}
