import Foundation

/// Describes one LUT we ship, plus the maths that produces it.
struct LUTDefinition: Sendable {
    let name: String
    let filename: String
    let category: String
    let summary: String
    /// The colour space the LUT expects on input. These are creative looks, not
    /// camera conversions: footage must already be in the working SDR space.
    let inputColorSpace: String
    let type: String
    let transform: @Sendable (RGB) -> RGB
}

/// Renders a `LUTDefinition` into standard `.cube` text.
///
/// Sample ordering follows the `.cube` convention: **red varies fastest, blue
/// slowest**. Entry `i` corresponds to
/// `r = i % size`, `g = (i / size) % size`, `b = i / (size * size)`.
/// `CubeLUTParser` stores samples in file order without reinterpreting them, so
/// this ordering is the contract the eventual 3D-texture upload must match.
struct LUTGenerator {
    let size: Int

    init(size: Int = 33) {
        precondition(size >= 2, "A LUT needs at least two samples per axis")
        self.size = size
    }

    /// Samples the transform across the cube and returns the clamped results in
    /// file order.
    func samples(for transform: (RGB) -> RGB) -> [RGB] {
        var result: [RGB] = []
        result.reserveCapacity(size * size * size)
        let last = Double(size - 1)
        for bIndex in 0..<size {
            for gIndex in 0..<size {
                for rIndex in 0..<size {
                    let input = RGB(Double(rIndex) / last, Double(gIndex) / last, Double(bIndex) / last)
                    result.append(ColorOps.clamped(transform(input)))
                }
            }
        }
        return result
    }

    func makeCubeText(name: String, transform: (RGB) -> RGB) -> String {
        var text = """
        # \(name)
        # Generated by Tools/LUTGenerator. Do not edit by hand.
        # Creative look for Rec.709 / working SDR input. Not a camera conversion LUT.
        # Sample order: red fastest, blue slowest.
        TITLE "\(name)"
        LUT_3D_SIZE \(size)
        DOMAIN_MIN 0.0 0.0 0.0
        DOMAIN_MAX 1.0 1.0 1.0

        """
        for sample in samples(for: transform) {
            text += String(format: "%.6f %.6f %.6f\n", sample.r, sample.g, sample.b)
        }
        return text
    }

    @discardableResult
    func write(_ definition: LUTDefinition, to directory: URL) throws -> URL {
        let url = directory.appendingPathComponent(definition.filename)
        let text = makeCubeText(name: definition.name, transform: definition.transform)
        try text.write(to: url, atomically: true, encoding: .utf8)
        return url
    }
}
